-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 17:10:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nb21o
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nb21o` ;

-- -----------------------------------------------------
-- Schema nb21o
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nb21o` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `nb21o` ;

-- -----------------------------------------------------
-- Table `nb21o`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nb21o`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nb21o`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT ZEROFILL NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nb21o`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nb21o`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nb21o`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT ZEROFILL NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nb21o`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nb21o`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nb21o`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC) VISIBLE,
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `nb21o`.`customer` (`cus_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `nb21o`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `nb21o`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `nb21o`;
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Claws and Paws', 'L.A.', '123 Main St.', 'CA', 90210, 8501234567, 'clawspaws@gmail.com', 'http://clawspaws.com', 50000, 'notes1');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Friends', 'Tallahassee', '135 Duval', 'FL', 32301, 8501236789, 'furryfriends@gmail.com', 'http://furryfriends.com', 55000, 'notes2');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Partners', 'Boca Raton', '255 West Dr.', 'FL', 33433, 5615552345, 'petpartners@gmail.com', 'http://petpartners.com', 60000, 'notes3');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Palace', 'Tallahassee', '55 Call St.', 'FL', 32304, 8502034444, 'petpalace@gmail.com', 'http://petpalace.com', 60000, 'notes4');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Purrs and Gurrs', 'Phoenix', '751 Louis Lane', 'AZ', 82345, 7034423333, 'purrsgurrs@gmail.com', 'http://purrsandgurrs.com', 55000, 'notes5');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Carols Critters', 'Tallahassee', '255 W Pensacola', 'FL', 32304, 8505562222, 'carolscritters@gmail.com', 'http://carolscritters.com', 60000, 'notes6');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'PetCo', 'Tallahassee', '34 W Call St.', 'FL', 32301, 8509091111, 'petco@gmail.com', 'http://petco.com', 70000, 'notes7');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'PetSmart', 'Boca Raton', '45 Military Trail', 'FL', 33433, 5612324444, 'petsmart@gmail.com', 'http://petsmart.com', 80000, 'notes8');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Birds and Co', 'NY', '811 4th St.', 'NY', 12202, 5165556079, 'birdsco@gmail.com', 'http://birdsco.com', 90000, 'notes9');
INSERT INTO `nb21o`.`petstore` (`pst_id`, `pst_name`, `pst_city`, `pst_street`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Club', 'Wellington', '18 Chase Drive', 'FL', 34333, 5612036777, 'petclub@gmail.com', 'http://petclub.com', 85000, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nb21o`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `nb21o`;
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'John', 'Son', '222 W Call St.', 'Tallahassee', 'FL', 32301, 8502223034, 'johnson@gmail.com', 23.55, 200.44, 'notes1');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Erica', 'Sans', '8 College Ave', 'Tallahassee', 'FL', 32301, 8506068832, 'ericasans@gmail.com', 58.99, 80.02, 'notes2');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Tom', 'Web', '66 Pinapple Lane', 'Boynton Beach', 'FL', 33437, 5616234401, 'tomweb@gmail.com', 209.34, 779.82, 'notes3');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Jack', 'Benz', '23 Duval St.', 'Tallahassee', 'FL', 32304, 8506022314, 'jackbenz@gmail.com', 0.0, 156.89, 'notes4');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Tyler', 'Hertz', '45 Tempest Lane', 'Sturgis', 'SD', 80234, 4076298076, 'tylerhertz@gmail.com', 152.43, 872.30, 'notes5');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Kory', 'Samson', '23 Airport Dr.', 'Tallahassee ', 'FL', 32304, 5612237734, 'korysamson@aol.com', 402.87, 2309.89, 'notes6');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Connor', 'Kinze', '42 College Ave', 'Orlando ', 'FL', 38655, 7723446706, 'connorkinze@gmail.com', 8.56, 8.56, 'notes7');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Gavin', 'Smith', '323 Prospect Ln.', 'Titusville', 'FL', 31231, 4045561012, 'gavinsmith@gmail.com', 15.59, 42.30, 'notes8');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sean', 'Strickland', '22 Champion Way', 'Ocala', 'FL', 35565, 3425622333, 'seanstrickland@gmail.com', 304.44, 854.24, 'notes9');
INSERT INTO `nb21o`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Emily', 'Green', '122 Feature', 'Tallahassee', 'FL', 32304, 5616344578, 'emilygreen@hotmail.com', 59.99, 203.47, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `nb21o`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `nb21o`;
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 2, 'pitbull', 'm', 50, 75, 3, 'brown', '2018-05-22', 'y', 'n', 'notes1');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 4, 'parakeet', 'f', 75, 200, 20, 'green/yellow', '2009-12-22', 'n', 'y', 'notes2');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 7, 'greyhound', 'm', 400, 600, 5, 'grey', '2018-05-14', 'y', 'n', 'notes3');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 8, 'english bulldog', 'f', 800, 1500, 1, 'grey/blue', '2023-01-22', 'n', 'n', 'notes4');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 10, 'golden retriever', 'm', 500, 850, 6, 'gold/brown', '2016-08-14', 'n', 'y', 'notes5');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 1, 'corn snake', 'm', 30, 80, 4, 'yellow/black', '2019-03-21', 'y', 'n', 'notes6');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 5, 'chiwawa', 'f', 450, 800, 14, 'brown/black', '2009-12-08', 'n', 'y', 'notes7');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 3, 'french bulldog', 'm', 1200, 1800, 2, 'grey', '2023-02-13', 'y', 'y', 'notes8');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 6, 'scorpion', 'f', 200, 250, 2, 'orange', '2022-05-16', 'y', 'n', 'notes9');
INSERT INTO `nb21o`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 9, 'french bulldog', 'f', 900, 1200, 7, 'black/white', '2012-09-23', 'n', 'n', 'notes10');

COMMIT;

